import fs from "node:fs/promises";
import path from "node:path";
import { artifacts } from "hardhat";

type AddressMap = Record<string, { BlockMail: string }>;

async function ensureDir(dir: string) {
  await fs.mkdir(dir, { recursive: true });
}

async function fileExists(p: string) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

export async function syncToShared(params: { chainId: number; mailboxAddress: string }) {
  // Assumes you run from packages/contracts (normal for Hardhat)
  const sharedChainDir = path.resolve(process.cwd(), "../shared/src/chain");

  // 1) Export ABI
  const artifact = await artifacts.readArtifact("BlockMail");
  const abiPath = path.join(sharedChainDir, "abi", "BlockMail.abi.json");
  await ensureDir(path.dirname(abiPath));
  await fs.writeFile(abiPath, JSON.stringify(artifact.abi, null, 2), "utf8");

  // 2) Export addresses.ts
  const addressesPath = path.join(sharedChainDir, "addresses.ts");

  let current: AddressMap = {};
  if (await fileExists(addressesPath)) {
    // Very small + safe parse: pull the JSON-ish object out of the TS file if it exists.
    // If you want simpler, delete addresses.ts and redeploy; it’ll be recreated.
    const text = await fs.readFile(addressesPath, "utf8");
    const match = text.match(/export const EOB_ADDRESSES = (\{[\s\S]*?\}) as const;/);
    if (match?.[1]) {
      try {
        current = JSON.parse(match[1]);
      } catch {
        current = {};
      }
    }
  }

  current[String(params.chainId)] = { BlockMail: params.mailboxAddress };

  const addressesTs = `// AUTO-GENERATED by packages/contracts/scripts/sync-shared.ts
// Do not edit by hand.

export const EOB_ADDRESSES = ${JSON.stringify(current, null, 2)} as const;

export function getBlockMailAddress(chainId: number): string {
  const entry = (EOB_ADDRESSES as Record<string, { BlockMail: string }>)[String(chainId)];
  if (!entry) throw new Error(\`No BlockMail address for chainId \${chainId}\`);
  return entry.BlockMail;
}
`;

  await ensureDir(sharedChainDir);
  await fs.writeFile(addressesPath, addressesTs, "utf8");

  console.log(`[sync] ABI -> ${abiPath}`);
  console.log(`[sync] addresses -> ${addressesPath}`);
}
