// AUTO-GENERATED by packages/contracts/scripts/sync-shared.ts
// Do not edit by hand.

export const EOB_ADDRESSES = {
  "31337": {
    "BlockMail": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
  }
} as const;

export function getBlockMailAddress(chainId: number): string {
  const entry = (EOB_ADDRESSES as Record<string, { BlockMail: string }>)[String(chainId)];
  if (!entry) throw new Error(`No BlockMail address for chainId ${chainId}`);
  return entry.BlockMail;
}
